apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:3.4.3
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_MASTER_PORT
              value: "7077"
          ports:
            - containerPort: 7077
              name: master-port
            - containerPort: 8080
              name: webui

---

apiVersion: v1
kind: Service
metadata:
  name: spark-master-internal
spec:
  selector:
    app: spark
  ports:
    - protocol: TCP
      port: 7077
      targetPort: 7077
      name: master-port
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: webui

---

apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  type: NodePort
  selector:
    app: spark
  ports:
    - protocol: TCP
      port: 7077
      targetPort: 7077
      nodePort: 32077
      name: master-port
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32080
      name: webui