apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-1
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: spark-1
  template:
    metadata:
      labels:
        app: spark-1
    spec:
      containers:
        - name: spark-worker-1
          image: bitnami/spark:3.4.3
          env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_MASTER
              value: spark://spark-master-internal:7077
          ports:
            - containerPort: 8081
              name: webui
